### ISSUE TITLE
data_for not returning expected

### ISSUE THREAD

**Issue by niartseoj** [cheezy/data_magic#22]
using data_magic (0.21)

I'm observing that tag with value of 042 is not returned as expected.

given a default.yml 
```
test_1:
  code: 042
```

When I run this 
```
class MyPage
    include DataMagic
end

page = MyPage.new
puts page.data_for :test_1
```

**Expected**
```
{"code"=>042}
```

**Actual**
```
{"code"=>34}
```

**Comment by presidentelect** [comment]
That is correct. A number beginning with a 0 is an octal and octal 042 is
decimal 34.

-----
Michael Hansen

**Comment by cheezy** [comment]
Try putting quotes around the value and it will be returned as a string.

**Comment by niartseoj** [comment]
Closing based on knowledge that quotes '042' returns as string.
